main:
  params: []
  steps:
    - getYesterdayDate:
        call: http.get
        args:
          url: https://yesterday-date-5d5xhd46ea-lz.a.run.app
        result: yesterdayDate
    - extractDate:
        assign:
          - yesterdayDateString: ${yesterdayDate.body}
    - retrieveAndStoreWeatherData:
        call: http.get
        args:
          url: https://ingestion-service-5d5xhd46ea-lz.a.run.app/
          query:
            location: "Stockholm"
            date: ${yesterdayDateString}
        result: PipelineResponse
    - validatePipelineResponse:
        switch:
          - condition: ${PipelineResponse.status_code == 200}
            steps:
              - workflow_end:
                  return: 'Workflow executed successfully'
          - condition: ${PipelineResponse.status_code != 200}
            steps:
              - handleError:
                  raise: '${"Error in workflow execution: " + PipelineResponse.body}'