name: Deploy api_sports-api-football-raw-workflow

on:
  push:
    branches:
      - api-football
    paths:
      - 'pipelines/api_sports-api-football-raw.yml'

jobs:
  deploy-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta'

    - name: Deploy Google Workflow
      run: |
        gcloud workflows deploy football-ingestion-workflow \
          --source pipelines/api_sports-api-football-raw-workflow.yml \
          --location europe-north1