name: Deploy clean-weather-consume

on:
  push:
    branches:
      - tinker_g
    paths:
      - 'pipes/clean-weatherprediction-consume/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta'

    - name: Configure Docker
      run: gcloud auth configure-docker gcr.io

    - name: Build Docker image
      run: |
        echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > pipes/clean-weatherprediction-consume/gcp-key.json
        docker build -t gcr.io/team-god/clean-weatherprediction-consume pipes/clean-weatherprediction-consume

    - name: Push Docker image
      run: docker push gcr.io/team-god/clean-weatherprediction-consume

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy clean-weatherprediction-consume-service \
          --image gcr.io/team-god/clean-weatherprediction-consume \
          --platform managed \
          --region europe-north1 \
          --concurrency 2 \
          --max-instances 2 \
          --allow-unauthenticated