name: Deploy Python Yesterday HTTP

on:
  push:
    branches:
      - main
    # paths:
    #   - 'pipes/python-yesterday-http/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy get_yesterday_date \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point get_yesterday_date \
          --region europe-north1 \
          --memory 128MB \
          --concurrency 2 \
          --max-instances 2 \
          --source ./pipes/python-yesterday-http.py