name: Deploy pytrends-api-search-clean

on:
  push:
    branches:
      - main
    paths:
      - 'pipes/pytrends-api-search-clean/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/pytrends-api-search-clean ./pipes/pytrends-api-search-clean

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/pytrends-api-search-clean

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy pytrends-api-search-clean-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pytrends-api-search-clean \
          --platform managed \
          --region europe-north1 \
          --concurrency 2 \
          --max-instances 2 \
          --allow-unauthenticated