name: Deploy Clean Weatherapp SQL

on:
  push:
    paths:
      - 'clean_weatherapp.sql'

jobs:
  deploy-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'bq'

    - name: Update BigQuery Query
      run: |
        bq query --use_legacy_sql=false --replace --destination_table=team-god.weather_data.clean_weatherapp < clean_weatherapp.sql