name: Deploy API Weather Raw

on:
  push:
    branches:
      - main
    # paths:
    #   - 'pipes/weatherapi-api-weather-raw/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build --cache-from=type=local,src=/tmp/.buildx-cache \
                     --cache-to=type=local,dest=/tmp/.buildx-cache-new \
                     -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/weatherapi-api-weather-raw ./pipes/weatherapi-api-weather-raw

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/weatherapi-api-weather-raw

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy weatherapi-api-weather-raw-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/weatherapi-api-weather-raw \
          --platform managed \
          --region europe-north1 \
          --concurrency 2 \
          --max-instances 2 \
          --allow-unauthenticated

    - name: Save Docker cache
      if: always()
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache-new
        key: ${{ runner.os }}-buildx-${{ github.sha }}