name: Deploy API Weather Raw

on:
  push:
    branches:
      - main
    # paths:
    #   - 'pipes/weatherapi-api-weather-raw/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/weatherapi-api-weather-raw ./pipes/weatherapi-api-weather-raw

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/weatherapi-api-weather-raw

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy weatherapi-api-weather-raw-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/weatherapi-api-weather-raw \
          --platform managed \
          --region europe-north1 \
          --concurrency 2 \
          --max-instances 2 \
          --allow-unauthenticated